### ISSUE TITLE
Firestore?

### ISSUE THREAD

**Issue by QuantForgeSoftware** [AshV/Firebase.Net#2]
This is a nice project. Are you planning on supporting Firestore? Whoops, sorry I did not know that google has finally released a C# project

**Comment by AshV** [comment]
Wow! good to know that Google started official C# sdk, can you share url please, I couldn't find it online

**Comment by QuantForgeSoftware** [comment]
https://github.com/googleapis/google-cloud-dotnet
https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/
